name: Zymbit Docs Action for Hugoify-ing API Docs
description: A Python container action that parses and reformats automatically-generated API docs.
author: Nick Anderegg
inputs:
  rawPath:
    description: The path to the directory containing the automatically-generated API docs.
    default: "./content/GENERATED/"
  outputPath:
    description: The path where the final rendered API docs will be placed.
    default: "./content/api/"
outputs:
  processingResults:
    description: A summary of the files that were processed.
runs:
  using: "docker"
  image: "Dockerfile"
