name: Zymbit Docs Action for Hugoify-ing API Docs
description: A Python container action that parses and reformats automatically-generated API docs.
author: Nick Anderegg
inputs:
  path:
    description: The path to the directory containing the automatically-generated API docs.
    default: "./content/GENERATED/"
outputs:
  testOutput:
    description: Output just for testing purposes.
runs:
  using: "docker"
  image: "Dockerfile"
