---
# Because this container requires a functioning Hugo repo to run properly,
# the intergration test really only checks that the container builds.
name: Integration Test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: zymbit-docs/actions-hugoify-api-docs@master
