---
# Because this container requires a functioning Hugo repo to run properly,
# the intergration test really only checks that the container builds.
name: Integration Test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Image build test
        id: buildtest
        run: |
          docker build -t zymbit-docs/hugoify-api-docs:latest .
