---
name: Lint

on:
  - push
  - pull_request

jobs:
  lint_python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Set up latest version of Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@v1

      - name: Install Python linter/formatter
        run: pip install black

      - name: Lint Python code
        run: |
          if ! black --check . ; then
            black --diff .
            exit 1
          fi


  lint_docker:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Lint Dockerfile
        run: hadolint Dockerfile
